### ISSUE TITLE
Adding OptionalLong and alike

### ISSUE THREAD

**Issue by juxeii** [akarnokd/RxJava2Jdk8Interop#1]
Would it be much of work to add [LongStream](https://docs.oracle.com/javase/8/docs/api/java/util/stream/LongStream.html) and [OptionalLong](https://docs.oracle.com/javase/8/docs/api/java/util/OptionalLong.html) for conversions?

**Comment by akarnokd** [comment]
RxJava doesn't support primitive types anyway so it only takes these to be converted to their boxed versions. For that, you don't really need this library to change.

**Comment by juxeii** [comment]
Here's an example on how I use a LongStream currently:
```
private Observable<Long> countStreamForTickFetch(final long endTime) {
	final LongStream counter = LongStream
		.iterate(1, i -> i + 1)
		.map(count -> endTime - count * tickFetchMillis + 1);
	return Observable.fromIterable(counter::iterator);
}
```
Is there an alternative with RxJava or RxJava2Extensions to replace the LongStream?

**Comment by akarnokd** [comment]
[LongStream.boxed()](https://docs.oracle.com/javase/8/docs/api/java/util/stream/LongStream.html#boxed--) let's you turn it into a `Stream<Long>`.

**Comment by juxeii** [comment]
Which version would be more performant(boxed seems expensive)?
And also, is there really no RxJava or RxJava2Extensions equivalent construct in producing infinite numbers?

**Comment by akarnokd** [comment]
> Which version would be more performant(boxed seems expensive)?

You could gain some performance with direct primitive support but at a very high development cost.

> producing infinite numbers?

Use `generate`.

```java
Flowable.generate(() -> 0, (s, e) -> { e.onNext(s); return s + 1; })
```

**Comment by juxeii** [comment]
Thx for explanations.
