### ISSUE TITLE
[Suggestion] FlowableInterop.fromOptional should use orElseGet instead of orElse

### ISSUE THREAD

**Issue by slisaasquatch** [akarnokd/RxJava2Jdk8Interop#11]
Right now it does `orElse(Flowable.empty())`. The problem with this is that if the input `Optional` is not empty, `onAssembly` will be called twice. Changing to `orElseGet(Flowable::empty)` should fix this. The same thing can also be done for `MaybeInterop`.

**Comment by akarnokd** [comment]
PR welcome.

**Comment by slisaasquatch** [comment]
Here's the pull request on 3.x https://github.com/akarnokd/RxJavaJdk8Interop/pull/12

I'm having trouble getting the 2.x branch to build for some reason. Here's the diff of what I did. I didn't create a pull request because it doesn't build.
https://github.com/akarnokd/RxJavaJdk8Interop/compare/master...saasquatch:orElseGet-2.x

**Comment by akarnokd** [comment]
Do you need this enhancement for 2.x? I don't plan to maintain 2.x further and RxJava 3 is little over 2 months away.

**Comment by slisaasquatch** [comment]
> Do you need this enhancement for 2.x? I don't plan to maintain 2.x further and RxJava 3 is little over 2 months away.

No I don't have any immediate need for it. I guess we can just ignore it.
