### ISSUE TITLE
CompletionStage interop methods are misleading

### ISSUE THREAD

**Issue by galderz** [akarnokd/RxJava2Jdk8Interop#2]
I've been playing around with the interop methods that take `CompletionStage` and I think they can be misleading.

For example, a naive user could create code like [`CompletableFuturesNotOk`](https://github.com/galderz/r3activex/blob/master/src/main/java/r3activex/CompletableFuturesNotOk.java) where it expects `future2` to be called after `future1` has completed but this is not what will happen. Because both interop methods take eager `CompletableStage` instances, the moment they're called the futures will be launched right there and then. So it could easily happen that `future2` is executed before `future1` has completed.

The correct way to deal with this would be for the `future2` to be launched when `future1` has completed, this can be done as shown in [`CompletableFuturesOk`](https://github.com/galderz/r3activex/blob/master/src/main/java/r3activex/CompletableFuturesOk.java).

I think you should have more generic different interop methods for CompletionStage that take lazy functions that create CompletionStage. For example, here's one I've created for `BiFunction` instances:

```java
static <A, B, V> Maybe<V> biFutureToMaybe(A a, B b, BiFunction<A, B, CompletionStage<V>> f) {
   return new Maybe<V>() {
      @Override
      protected void subscribeActual(MaybeObserver<? super V> observer) {
         f.apply(a, b).whenComplete(
            (v, t) -> {
               if (t != null)
                  observer.onError(t);
               else if (v != null)
                  observer.onSuccess(v);
               else
                  observer.onComplete();
            }
         );
      }
   };
}
```

You could have just one method that takes `Supplier<CompletionStage>` but you'd often have users having to create lambdas that capture external variables.

Cheers,
Galder

**Comment by akarnokd** [comment]
Sounds like you actually misunderstood the `CompletionStage` API instead. Unlike the RxJava constructs, `CompletionStage` and `CompletableFuture` represent an ongoing or already terminated computation. In other terms they are eager and RxJava is generally deferred: one has to call `subscribe` to get the operations going.

RxJava has tools to make computation deferred: `defer`, `fromCallable`, `flatMap`, `using`, etc. For example, if there is a method that starts some computation and returns a `CompletionStage` of it, you can defer its creation/execution until subscription time, and thus its conversion to an RxJava type with `defer` for example:

```java
Single.defer(() -> SingleInterop.fromFuture(methodReturningStage(params)))
.subscribe(/* ... */);
```

> suggestion to improve/extend your

Your post didn't sound like a feature request but as an bug/complaint of the library deliberately/erroneously misleading the user about what the method does.

**Comment by akarnokd** [comment]
Also your `biFutureToMaybe` violates the [`Maybe` protocol](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Maybe.html).

**Comment by galderz** [comment]
> Also your biFutureToMaybe violates the Maybe protocol.

Through further testing I realised ^

The code I use now looks like this:

```java
   static <A, B, T> Maybe<T> toMaybe(A a, B b, BiFunction<A, B, CompletionStage<T>> f) {
      return Maybe.create(source -> {
         f.apply(a, b).whenComplete(
            (x, t) -> {
               if (t != null) {
                  source.onError(t);
               } else if (x != null) {
                  source.onSuccess(x);
               } else {
                  source.onComplete();
               }
            }
         );
      });
   }
```

^ seems to work fine, or would you use `Maybe.defer` instead?

**Comment by akarnokd** [comment]
If you don't want the result to be cached then it is fine.

**Comment by galderz** [comment]
What do you mean the result being cached?
